ALTER TABLE schools ADD COLUMN short_name VARCHAR(100) NULL;
ALTER TABLE schools ADD COLUMN tagline VARCHAR(255) NULL;
ALTER TABLE schools ADD COLUMN city VARCHAR(100) NULL;
ALTER TABLE schools ADD COLUMN region VARCHAR(100) NULL;
ALTER TABLE schools ADD COLUMN phone VARCHAR(50) NULL;
ALTER TABLE schools ADD COLUMN favicon_path VARCHAR(500) NULL;
